WORLD_SIZE: int = 20
BLOCK_SIZE: int = 32

WIDTH: int = WORLD_SIZE * BLOCK_SIZE
HEIGHT: int = WORLD_SIZE * BLOCK_SIZE

TITLE: str = 'Pacman'
FPS: int = 60

PLAYER_SPEED: int = 5
IMMUNITY_TIME: int = 2000
MAX_HEALTH: int = 3